[package]
name = "columbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.2.0"
rusqlite = "0.29.0"
clap = "2.33"
rand = "0.8"